# Generated by Django 3.2.25 on 2024-03-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240321_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../https://res.cloudinary.com/dgzf4ydy2/image/upload/v1710446165/default_profile_yjhef1.jpg', upload_to='images/'),
        ),
    ]
