# Generated by Django 3.2.4 on 2024-05-25 12:03

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_post_image'),
        ('bookmarks', '0003_auto_20240525_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='bookmarked_post',
            new_name='post',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('owner', 'post')},
        ),
    ]
