# Generated by Django 3.2.4 on 2024-05-29 20:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_post_image'),
        ('dislikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='post',
            new_name='dislike_post',
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('owner', 'dislike_post')},
        ),
    ]
